# Generated by Django 3.1.4 on 2020-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelwithfilefield',
            name='file_field',
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='code_field',
            field=models.CharField(default='not found', max_length=5000),
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='complexity_field',
            field=models.CharField(default='logarithmic', max_length=30),
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='fname_field',
            field=models.CharField(default='solve', max_length=30),
        ),
    ]
