# Generated by Django 3.1.4 on 2020-12-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compx', '0002_auto_20201231_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='code_field',
            field=models.TextField(default='not found'),
        ),
    ]
