# Generated by Django 3.1.4 on 2021-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compx', '0003_auto_20201231_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithfilefield',
            name='complexity_key',
            field=models.CharField(default='exponential', max_length=30),
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='time1_field',
            field=models.CharField(default='10', max_length=30),
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='time2_field',
            field=models.CharField(default='20', max_length=30),
        ),
        migrations.AddField(
            model_name='modelwithfilefield',
            name='time3_field',
            field=models.CharField(default='30', max_length=30),
        ),
    ]
